// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgEwI2G9t6FFO4BRWf5Dsd7190sd732zs',
    appId: '1:735737738575:web:16ff54cb484b5a2c7dc13a',
    messagingSenderId: '735737738575',
    projectId: 'tp-flutter-firebase-7476d',
    authDomain: 'tp-flutter-firebase-7476d.firebaseapp.com',
    storageBucket: 'tp-flutter-firebase-7476d.appspot.com',
    measurementId: 'G-DDNRF299QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBccyfncqhhC_T6WB5VIG0EON9sdHRTvcY',
    appId: '1:735737738575:android:9200f552c7eb21f77dc13a',
    messagingSenderId: '735737738575',
    projectId: 'tp-flutter-firebase-7476d',
    storageBucket: 'tp-flutter-firebase-7476d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuTfMGdKeGGTMzWqj6G8t9LI7wZ7SU_0Y',
    appId: '1:735737738575:ios:82f1a60a888308407dc13a',
    messagingSenderId: '735737738575',
    projectId: 'tp-flutter-firebase-7476d',
    storageBucket: 'tp-flutter-firebase-7476d.appspot.com',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuTfMGdKeGGTMzWqj6G8t9LI7wZ7SU_0Y',
    appId: '1:735737738575:ios:82f1a60a888308407dc13a',
    messagingSenderId: '735737738575',
    projectId: 'tp-flutter-firebase-7476d',
    storageBucket: 'tp-flutter-firebase-7476d.appspot.com',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgEwI2G9t6FFO4BRWf5Dsd7190sd732zs',
    appId: '1:735737738575:web:99bfbf16c5fe8cd77dc13a',
    messagingSenderId: '735737738575',
    projectId: 'tp-flutter-firebase-7476d',
    authDomain: 'tp-flutter-firebase-7476d.firebaseapp.com',
    storageBucket: 'tp-flutter-firebase-7476d.appspot.com',
    measurementId: 'G-FS1N24ELR4',
  );

}